max_action_dim: 24
max_state_dim: 24
max_views: 3
data_groups:

  robotwin_robot:
    handover_mic_25_11_02_v2.1:
      path: /home/dell/Datasets/handover_mic_25_11_02_v2.1
      view_map:
        image_1: observation.images.image_1
        image_2: observation.images.image_2
        image_3: observation.images.image_3
